const menu = [
    {
        id: 1,
        title: 'buttermilk pancakes',
        category: 'breakfast',
        price: 15.99,
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2019/7/11/0/FNK_the-best-pancakes_H_s4x3.jpg.rend.hgtvcom.616.462.suffix/1562853903667.jpeg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
        id: 2,
        title: 'diner double',
        category: 'lunch',
        price: 13.99,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA4CCsHplaw-VXev2lC-LI39bdofmO5SmNBder1JR1jgHuazzsV1-YV71jLucLnmNV6rw&usqp=CAU',
        desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
        id: 3,
        title: 'godzilla milkshake',
        category: 'shakes',
        price: 6.99,
        img: 'https://i.ytimg.com/vi/GUrCsJ3pTGA/sddefault.jpg',
        desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
        id: 4,
        title: 'country delight',
        category: 'breakfast',
        price: 20.99,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5KMPMY_1WA5QKWobMaR5KpG0BW3MDVSjY0O8nBDQvHvVCav5VWAnQDYe-5M_P9YVe118&usqp=CAU',
        desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
        id: 5,
        title: 'egg attack',
        category: 'lunch',
        price: 22.99,
        img: 'http://karthfoodfactory.com/wp-content/uploads/2020/12/10.png',
        desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
        id: 6,
        title: 'oreo dream',
        category: 'shakes',
        price: 18.99,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS83NQP4alWmpxKZfVLPsKsUKLyEtGkEkiHcA&usqp=CAU',
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 7,
        title: 'bacon overflow',
        category: 'breakfast',
        price: 8.99,
        img: 'https://whenisdinner.com/wp-content/uploads/2019/06/Chicken-Bacon-Ranch-Poppers-Horiz.jpg',
        desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
        id: 8,
        title: 'american classic',
        category: 'lunch',
        price: 12.99,
        img: 'https://cdn.theculturetrip.com/wp-content/uploads/2017/05/nathans.jpg',
        desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
        id: 9,
        title: 'quarantine buddy',
        category: 'shakes',
        price: 16.99,
        img: 'https://www.khuab.com/wp-content/uploads/2020/06/breakfast-690128_1920.jpg',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
];
export default menu;